import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import pg from "pg";

const TABLES = [
  "pillars",
  "events",
  "content_posts",
  "brand_voice_notes",
  "past_posts",
  "copywriter_rules",
  "copywriter_feedback",
  "content_ideas",
  "saved_items",
  "media_assets",
  "team_members",
  "voice_profiles",
] as const;

// Resolve relative to this script file (scripts/src/) → ../../artifacts/api-server/src/...
// — not process.cwd(), which differs depending on how the script is invoked.
const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(SCRIPT_DIR, "../../artifacts/api-server/src/data-snapshot.json");

async function main(): Promise<void> {
  if (!process.env["DATABASE_URL"]) {
    throw new Error("DATABASE_URL is required");
  }

  const pool = new pg.Pool({ connectionString: process.env["DATABASE_URL"] });
  const tables: Record<string, unknown[]> = {};

  for (const t of TABLES) {
    const { rows } = await pool.query(`SELECT * FROM ${t} ORDER BY id`);
    tables[t] = rows;
    console.log(`  ${t.padEnd(24)} ${String(rows.length).padStart(4)} rows`);
  }

  const snapshot = {
    version: new Date().toISOString(),
    note: "Generated by `pnpm snapshot`. Loaded by api-server in production to seed an empty prod DB. Do not edit by hand.",
    tables,
  };

  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, JSON.stringify(snapshot, null, 2) + "\n");
  console.log(`\nWrote ${OUT}`);
  console.log(`Snapshot version: ${snapshot.version}`);

  await pool.end();
}

main().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
