export interface ChangelogEntryStatic {
  sortKey: string;
  date: string;
  category: string;
  summary: string;
  capabilities: string[];
}

// Virtu Ferries (brand_id 1) — full operational + strategy knowledge.
export const knowledgeChangelog: ChangelogEntryStatic[] = [
  {
    sortKey: "2026-05-12-d",
    date: "2026-05-12",
    category: "Social Media",
    summary: "Reworked the Social Media strategy page so each topic gets its own clearly separated section instead of being squashed into one block. Platforms and Posting Cadence are now two distinct sections, and every section has a proper header with an eyebrow label, an icon, a bold title and a hairline rule — no more tiny coloured dashes.",
    capabilities: [
      "Platforms section now shows only the channels and handles per market (no cadence noise). Each market is its own card with audience + framing + an optional brand-tinted note pinned underneath",
      "Posting Cadence is a brand-new section showing each platform's posting volume in a clean two-column grid, grouped by market, so the user can scan 'how often per channel' at a glance without re-reading the platforms list",
      "Section dividers replaced: the old 8×2px coloured dash next to each h2 is gone. Every section now has a SectionHeader with uppercase eyebrow + lucide icon, a vertical accent bar, the bold title, an optional one-line subtitle, and a fading hairline rule underneath. Sections are also further apart vertically (space-y-20)",
      "Content Pillars use zero-padded numerals (01, 02, …) in the brand primary tint instead of near-invisible white/10. Cross-Posting bullets now show actual disc markers in brand colour instead of unmarked lines. No data/schema changes — purely a presentation rewrite",
    ],
  },
  {
    sortKey: "2026-05-12-c",
    date: "2026-05-12",
    category: "Gozo Highspeed",
    summary: "Added a Hop-On Hop-Off page to the Gozo Highspeed brand hub. Sidebar entry under Brand → Hop-On Hop-Off (GHS only). Page focuses on the three things that actually matter to a customer: prices, the 14 bus stops, and the daily timetable for each run.",
    capabilities: [
      "New page at /hop-on-hop-off with three sections: prices (€30 adult / €20 child 4–10 / FREE infant 0–3, 1-day validity), the 14-stop loop starting and ending at Mġarr Harbour, and a sticky-first-column timetable showing all 9 daily departure runs",
      "GHS palette throughout — primary blue #1d3289 for stop numbers and accents, red #ea2d3f reserved for the seasonal note that the 15:45 Mġarr Harbour departure does not operate between November and March",
      "Sidebar route is brand-conditional (only appears when active brand is Gozo Highspeed) so it does not pollute the Virtu Ferries hub. Page itself shows a graceful EmptySection if visited under a non-GHS brand",
    ],
  },
  {
    sortKey: "2026-05-12-b",
    date: "2026-05-12",
    category: "Content Calendar",
    summary: "Added a one-click \"add another channel\" action right on every post row in the Content Calendar. After saving a post as Facebook-only (or Instagram-only, or any single channel), the channels you have NOT picked appear as faint icons next to the active platform — click one to instantly publish the same post on that channel too, no need to open the edit modal.",
    capabilities: [
      "PostRow now renders ghost icons for every unselected channel beside the active platform icons. Each ghost icon has a small + badge in the corner so the affordance reads as 'add this'. Click → PATCH /api/content/posts/:id with the new platform string and refetch the month",
      "Virtu Ferries logic: English-market posts can flip Facebook ↔ Both (FB+IG) or Instagram ↔ Both with a single click; cross_post is set to true. Italian-market posts stay FB-only (no add icon shown) since the brand only operates Italian on Facebook",
      "Gozo Highspeed logic: comma-separated platform list (Facebook,Instagram,Story) supports any combination. Adding a channel appends to the list; the row immediately reflects the new icons after the refetch",
      "Hidden in selection mode and on profile-change entries (which have no platform). Loading spinner replaces the icon while the PATCH is in flight, and click events stopPropagation so the row's open-edit handler doesn't fire",
    ],
  },
  {
    sortKey: "2026-05-12-a",
    date: "2026-05-12",
    category: "Content Calendar",
    summary: "Made image/video uploads on the Gozo Highspeed Content Calendar a first-class action. The attachment field is now visible by default on every new GHS post and uses the GHS palette so it stops feeling like a Virtu Ferries control bolted on.",
    capabilities: [
      "New posts on the GHS calendar default to attachment_type=\"upload\" so the dropzone is visible immediately — no need to discover the toggle. Virtu Ferries keeps its existing default of \"none\"",
      "Attachment toggle (None / Upload / Link) and dropzone hover state now use GHS Brand Blue (#1d3289) when the active brand is Gozo Highspeed; Virtu Ferries keeps #1e82b4. The active brand's identity now flows into the calendar form instead of being overridden",
      "Field label on GHS reads \"Visual — image or video — optional\" instead of the generic \"Attachment (optional)\", matching how the GHS team talks about creative",
      "GHS dropzone reformatted to the same vertical, centred layout as Virtu (icons + 'Click to upload an image or video' + accepted formats) so the affordance is unmissable",
    ],
  },
  {
    sortKey: "2026-05-11-e",
    date: "2026-05-11",
    category: "Brand Identity",
    summary: "Typography section on the Assets page is now a full weight ladder. Each Montserrat weight has its own card showing the weight name, a real sample line rendered at hero scale in that exact weight, and a clear \"use for\" guideline so designers know when to reach for which weight.",
    capabilities: [
      "TypographyBlock weights now carry a `usage` field (Virtu Ferries: Light → ExtraBold; Gozo Highspeed: Black → Regular). Usage strings explain the role of each weight (hero claim vs section heading vs body) so the choice is unambiguous",
      "Assets page Typography section rebuilt — replaced the old two-column \"first three / last three\" split with a single ladder, one card per weight, sample line rendered at text-3xl/4xl in the actual weight so the visual hierarchy is obvious at a glance",
      "Agent prompt formatter (formatAssets in lib/brand-knowledge/src/prompt.ts) updated to emit the per-weight usage line alongside the sample, so the AI agent now knows which weight to recommend in copy briefs",
    ],
  },
  {
    sortKey: "2026-05-11-d",
    date: "2026-05-11",
    category: "AI Agent",
    summary: "Injected the FULL Gozo Highspeed Brandbook (every page of the 2024 PDF) into the AI agent's knowledge base. The prompt formatter now also dumps the visual identity block (colours, typography, logo lockups, do's and don'ts) for every brand, so the agent can reason about palette, font, and logo-usage rules — not just copy.",
    capabilities: [
      "Prompt formatter (lib/brand-knowledge/src/prompt.ts) extended with a new \"Assets & visual identity\" section that lists brand colours (with hex + CMYK descriptions), typography weights with sample lines, logo lockup variants, logo mark anatomy (where present), and the do's / don'ts. Applies to BOTH brands automatically — Virtu Ferries agent now also gets its palette, Mediterranean V/A/B mark anatomy, and logo rules in-prompt",
      "Gozo identity expanded with full brandbook personality block — Reliable, Efficient, Customer-Centric, Friendly each with its rationale — surfaced via keyMessages so the agent can quote them",
      "Gozo tone of voice rewritten verbatim from the brandbook (Clear / Professional / Engaging / Energetic with full descriptions)",
      "Gozo brand story now matches the brandbook's Brand Introduction page word-for-word, including the closing mantra line",
      "Gozo assets.logos populated with the six official lockups (icon, wordmark, wordmark + Operated-By tagline — each in full-colour and white-reversed) so the agent knows which mark to recommend in which context",
      "Gozo logo don'ts expanded from 4 to 7 entries to cover all six brandbook \"Logo Incorrect Uses\" (move/shrink elements, change colours, warp, stretch, drop shadow, add/remove elements) plus the existing background-contrast rule",
      "Hero claims from the brandbook mockups (\"Malta to Gozo in 45 Minutes\", \"Valletta → Gozo in Only 45 Minutes\", ferry-schedule poster format) added to keyMessages so the agent can echo them in copy",
    ],
  },
  {
    sortKey: "2026-05-11-c",
    date: "2026-05-11",
    category: "Brand Identity",
    summary: "Loaded the official Gozo Highspeed Brandbook (2024 edition) into the hub. Brand Identity, Assets palette, and the AI agent's system prompt now reflect the real brand — personality (Reliable / Efficient / Customer-Centric / Friendly), tone (Clear / Professional / Engaging / Energetic), positioning, mantra, and the official two-colour palette.",
    capabilities: [
      "Brand Identity page populated with the brandbook story, four tone-of-voice cues, key messages (incl. positioning + mantra), and explicit do/don't copy rules — all auto-feed into the agent system prompt via formatBrandKnowledgeAsPrompt",
      "Assets page now shows the official two-colour palette only — Brand Blue #1d3289 (C100 M94 Y13 K2) and Brand Red #ea2d3f (C2 M96 Y77 K0) — plus a Montserrat (Black → Regular) typography block and brandbook-derived logo do/don't list",
      "Brand picker chrome (sidebar accents, share-link headers) refreshed for Gozo Highspeed: primary #1d3289, accent #ea2d3f. seedBrandsIfMissing now updates the brands row when palette/tagline drift from the canonical seed, so dev and prod stay in sync without a manual SQL push",
      "AI system prompt for Gozo rewritten around the brandbook's four personality pillars + tone + positioning + mantra, and explicitly forbids reusing Virtu Ferries (Malta ↔ Sicily) copy",
    ],
  },
  {
    sortKey: "2026-05-11-b",
    date: "2026-05-11",
    category: "Hub Cleanup",
    summary: "Moved 'Saved for Later' under the Social Media group in the sidebar (both brands) and renamed it to 'Ideas' so the inspiration bin sits next to where it actually feeds — between Strategy and Content Calendar.",
    capabilities: [
      "Sidebar 'Social Media' group is now: Strategy / Ideas / Content Calendar / Skipped Posts",
      "Top-level 'Saved for Later' nav entry removed; the underlying /saved route, page, and saved_items DB table are unchanged so existing bookmarks and links still work",
    ],
  },
  {
    sortKey: "2026-05-11-a",
    date: "2026-05-11",
    category: "Hub Cleanup",
    summary: "Temporarily removed four under-baked features from the sidebar of both brands — Social Expert, Content Ideas, Monthly Planning, and Copywriter — so the hub stays focused on what's actually being used day-to-day. Underlying API routes and DB tables are untouched, so the features can be brought back without data loss when they're rebuilt.",
    capabilities: [
      "Sidebar 'Social Media' group on both Virtu and Gozo Highspeed now shows only: Strategy / Content Calendar / Skipped Posts (Social Expert, Content Ideas, Monthly Planning, Copywriter entries removed)",
      "Page files removed: social-media-expert.tsx, content-ideas.tsx, monthly-planning.tsx, copywriter.tsx, copywriter-library.tsx, copywriter-rules.tsx, copywriter-combined.tsx; corresponding routes (/social-media-expert, /content-ideas, /monthly-planning, /copywriter, /copywriter-library, /copywriter-rules) deleted from App.tsx so the URLs now 404 inside the SPA",
      "Server-side endpoints, copywriter rules/feedback DB tables, and content_ideas table left in place — no destructive backend changes — so reintroducing the features later just means putting the React pages back",
    ],
  },
  {
    sortKey: "2026-05-07-b",
    date: "2026-05-07",
    category: "Content Calendar",
    summary: "Added a 'Skipped' status alongside Draft / Approved / Posted in the Content Calendar (both Virtu and GHS). Skipped posts disappear from the calendar grid and live on a new /skipped-posts archive page where they can be restored as drafts or deleted permanently.",
    capabilities: [
      "Status pill in the post detail modal now offers Draft / Approved / Posted / Skipped on both brands",
      "Skipped posts are hidden from the calendar's monthly view so they don't clutter planning, but the underlying row is preserved in content_posts with status='skipped'",
      "New 'Skipped Posts' sidebar entry under Social Media (both brands) opens a brand-scoped table — Date / Channel / Title&Caption / Pillar — sorted newest-first across all months",
      "Each row has Restore (sets status back to 'pending'/Draft, returns to calendar) and Delete (permanent) actions; new GET /api/content/posts/skipped endpoint serves the archive",
    ],
  },
  {
    sortKey: "2026-05-07-a",
    date: "2026-05-07",
    category: "Internal Tools",
    summary: "Added a dedicated 'Nico' page for our videographer to drop raw asset links into. Plain table — Type / Date / Link — the team picks them up from there. Brand-scoped (Virtu only in the sidebar today, but the table is generic).",
    capabilities: [
      "New /nico page in the Virtu sidebar with a table view (Type, Date, Link, optional notes) and an Add button",
      "Backed by a new nico_links table and /api/nico-links CRUD endpoints (GET / POST / PATCH / DELETE), brand-scoped via x-brand-slug like every other resource",
      "Type field is open text on the server (so Nico can type anything if he needs to) but the UI offers Video / Voiceover / Image / Audio / Other as quick-pick chips",
      "Treated as user-content in the prod bootstrap — once prod has rows, dev edits don't overwrite them",
    ],
  },
  {
    sortKey: "2026-04-25-f",
    date: "2026-04-25",
    category: "Excursions",
    summary: "Enriched the four detailed Sicily excursions (Mt. Etna & Catania Winter, Ragusa Ibla / Modica / Scicli Winter, Taormina & Mt. Etna Summer, Catania & Mt. Etna Summer) with full schedule, pricing (incl. EU ETS breakdown), itinerary, local transport add-on and operational caveats. Added a 'Malta Excursion (inbound)' entry for the day-trip we sell to Sicilian and Italian visitors. Auto-feeds into the agent prompt so service-led answers ('when does Etna run?', 'how much for two adults and a child?', 'is the bus included?') are grounded in the published catalogue. Excursion type extended with optional schedule / pricing / itinerary fields.",
    capabilities: [
      "Mt. Etna & Catania (Winter, Oct 2025 – Apr 2026) — Adults €157.60, Children €101.60 (4 to under 14), Under 4 FREE; underlying €153 + €4.60 ETS / €97 + €4.60 ETS; min 10 pax. Thursdays + Sundays (1 Oct 2025 – 4 Jan 2026 and April 2026); Sundays 5 Jan – 31 Mar slot is taken by Ragusa/Modica/Scicli instead",
      "Mt. Etna & Catania schedule — Thursdays: DEP MLA 06:30 / ARR POZ 08:15 / DEP POZ 21:30 / ARR MLA 23:15. Sundays: DEP POZ 20:30 / ARR MLA 22:15",
      "Ragusa Ibla, Modica & Scicli (Winter, Oct 2025 – Apr 2026) — Adults €137.60, Children €97.60; underlying €133 + €4.60 ETS / €93 + €4.60 ETS; min 10 pax. Sundays (5 Jan – 31 Mar 2026): DEP MLA 06:30 / DEP POZ 19:30 / ARR MLA 21:15. Wednesdays (11 Mar – 29 Apr 2026): DEP MLA 07:30 / DEP POZ 19:30",
      "Taormina & Mt. Etna (Summer, 7 May – 27 Sep 2026) — Adults €159, Children €110 (incl. EU ETS), Under 4 FREE; min 15 pax. Thursdays (7 May – 21 Jun) + Sundays (3 May – 27 Sep). Catamaran returns at 21:30",
      "Catania & Mt. Etna (Summer, 25 Jun – 24 Sep 2026) — Adults €159, Children €110 (incl. EU ETS), Under 4 FREE; min 15 pax. Every Thursday: DEP MLA 07:30 / ARR POZ 09:15 / DEP POZ 21:30 / ARR MLA 23:15",
      "All excursions — Local transport in Malta (Hotel/Harbour/Hotel) is an optional €15 per person add-on (VAT incl.); pick-up points and timings on virtuferries.com",
      "All excursions are subject to fuel surcharge (Company reserves the right without notice), itinerary may change for weather, Conditions of Carriage apply",
      "All excursions include: arrival at Pozzallo, air-conditioned coaches with English-speaking guides, sampling stop for wines/almond sweets/honey on the Etna route (no obligation to buy), High-Speed Catamaran return",
      "Etna stop is the Sylvestri Crater at 2,000m; Catania highlights: Piazza del Duomo, Via Etnea, fish market, Roman Amphitheatre, Villa Bellini",
      "Ragusa/Modica/Scicli highlights: Gagliardi's Duomo (Ragusa Ibla), Modica Bassa with Duomo di San Giorgio (Cioccolato di Modica), Scicli with Palazzo Beneventano",
      "Taormina highlights: 206m above sea level, Greek Theatre (Hellenic 4 BC, summer classical plays), Corso Umberto, panoramic view over Giardini Naxos",
      "Syracuse & Marzamemi (Summer) — kept in catalogue but schedule/pricing/itinerary not yet captured; agent must verify the live site before quoting specifics",
      "Malta Excursion (inbound, year-round) — added as a day trip for Sicilian and Italian visitors travelling FROM Pozzallo TO Malta. Sell Malta as: compact, English-speaking, history-soaked archipelago; Independence 1964, EU since 2004; megalithic temples that predate the Pyramids and Stonehenge (UNESCO); Maltese is the only Semitic language using the Latin alphabet; long shared history with Sicily and Southern Italy in the Kingdom of the Two Sicilies until 1530 (when the Knights of St John arrived). Schedule and pricing not yet captured — verify live site",
    ],
  },
  {
    sortKey: "2026-04-25-e",
    date: "2026-04-25",
    category: "Onboard Experience",
    summary: "Expanded the Virtu Ferries Onboard Experience knowledge slot with the full 'Off We Go' on-board guide — boarding flow and decks, lounges and seating, outside seating / shop / entertainment, cafeterias and bars, family / car / pet travel, and practical info (smoking, charging, Purser). Auto-feeds into the agent prompt so service-led answers (where to sit for the best view, where to find the bar, what to do with kids on board, etc.) are grounded in the published guide.",
    capabilities: [
      "Boarding: vessel entrance is on Main Deck (garage deck) via accommodation gangway; lift available between Main and Upper Decks (ask Cabin Crew); reduced-mobility / pushchair passengers board on Main Deck via the garage ramp — notify staff at check-in",
      "Decks: Upper Deck has 5 lounges — Fore (front, best sea views), Aft (rear), Starboard (right), Port (left), and St. Elmo amidships (RESERVED for commercial vehicle drivers). Bridge Deck has the exclusive Club Lounge",
      "Seating: free choice in every lounge; capacity scaled down to 800 (vessel can take 1,000) for comfort, outdoor seating over and above; mostly reclining seats, small number of armchairs and sofas",
      "Stability tip: in adverse sea conditions the most stable seats are in the Starboard and Port Lounges, on the side furthest from the windows",
      "Outside Seating Areas open throughout the voyage — Grand Harbour Valletta view leaving Malta, Sicilian coast view leaving Pozzallo",
      "Hybleum on-board shop — fragrances 20% less than shops, packages only available in restricted travel retail; souvenirs, toys, wines, spirits, costume jewellery; coach tickets and taxi bookings to anywhere also sold here",
      "On-board entertainment: slot machines (regulated), movies on screen",
      "Cafeterias / Bars: 3 on board (Fore Lounge, Aft Lounge, Club) — hot/cold snacks, soft drinks, wines/spirits; every bar offers sweet and savoury gluten-free options",
      "Travelling with children: must be supervised by an adult at all times incl. Outside Seating Area; nappy changer on board (ask Cabin Crew); free colour crayons and colouring material from Cabin Crew, for the child to keep",
      "Travelling by car: drive-up check-in (no need to leave the vehicle); on arrival, drivers are called over PA to proceed to garage ahead of other disembarking passengers; 3 Main Deck exits closest to the car — Starboard Lounge, Port Lounge, far end of Aft Lounge",
      "Travelling with a pet: must inform staff at check-in AND a Cabin Crew member on boarding; refer detailed enquiries to the published Pet Policy",
      "Smoking: NOT permitted anywhere on the vessel except the designated area in the Outside Seating Area",
      "Mobile charging: designated charging points on board — ask the Cabin Crew",
      "Club Class additions: dedicated Club Lounge on Bridge Deck with reclining seats + footrests; opens onto its own Outside Seating Area; complimentary orange juice and a newspaper on boarding; dedicated Club check-in desk + priority disembarkation; cars in Club get a priority embarkation lane (commercial vehicles in Club are NOT assigned to the Club Vehicle lane)",
      "Last-minute upgrades to Club Class are possible on board — ask a Cabin Crew member, cost is minimal",
      "Single point of contact during the crossing: the Purser and the Cabin Crew",
    ],
  },
  {
    sortKey: "2026-04-25-d",
    date: "2026-04-25",
    category: "Customer Promise",
    summary: "Added the published Virtu Ferries 'no-penalties, no-hidden-fees' customer promise as a dedicated knowledge slot and standalone page. The agent must use these as the source of truth whenever passengers ask about refunds, changes, name changes, vehicle classification, baggage or booking fees, and must always quote the 'Not applicable on special offers' caveat alongside.",
    capabilities: [
      "Refunds: full refund on a paid passenger ticket if cancelled at least 24 hours prior to departure; no no-show penalty on passenger tickets",
      "Free changes: no penalties for name changes (passenger or driver & vehicle); no charges to move travel date on either leg, within the same fare basis and subject to space",
      "Vehicle classification: Land Rovers, pick-ups and panel vans up to 4.5m pay light vehicle tariffs when used non-commercially; passenger mini-vans pay light vehicle tariffs; heavily discounted rates for commercial vehicles up to 5.9m",
      "No hidden fees: no personal baggage over-weight charges, no booking admin charges, no credit card payment fees, no extra charge for new tickets bought at check-in",
      "Mandatory caveat to state alongside any of the above promises: 'Not applicable on special offers'",
    ],
  },
  {
    sortKey: "2026-04-25-c",
    date: "2026-04-25",
    category: "Excursions",
    summary: "Added a Sicily Excursions page and content slot to the brand hub. Captures the destination context Maltese travellers care about (landscape, food, heritage) plus the named excursion catalogue (5 routes split across Winter and Summer). Auto-feeds into the agent's brand prompt for Sicily-flavour copy.",
    capabilities: [
      "Sicily context: 5 million population; joined the Italian state in 1860; ever-changing landscape; characteristic hill-top towns rebuilt after the 1693 earthquake; Magna Graecia heritage",
      "Food & drink to take home: Torroncini (nougat), Pasta di Mandorla (almond cakes), Limoncello, Vino alla Mandorla, Averna (amaro)",
      "Heritage anchors: Greek Temples of Agrigento, Roman Mosaics at Piazza Armerina, Siracusa (Greek/Roman Theatres + Cathedral / former Temple of Athena in Ortygia), baroque cities of Noto/Ragusa/Modica minutes from Pozzallo, plus Palermo, Erice and Cefalu. The Iblei Mountain Range is described as picturesque; many towns in the Provincia di Ragusa are UNESCO Heritage Sites",
      "Named excursions catalogue (5 known excursions captured from the source — may be incomplete; verify the live site before publishing customer-facing claims) — Winter: 'Mt. Etna & Catania', 'Ragusa Ibla, Modica & Scicli'; Summer: 'Taormina & Mt. Etna', 'Syracuse & Marzamemi', 'Catania & Mt. Etna'",
      "Authoritative tagline available for excursion copy: 'There is only one thing we are certain of — you will enjoy Sicily'",
    ],
  },
  {
    sortKey: "2026-04-25-b",
    date: "2026-04-25",
    category: "Onboard Experience",
    summary: "Launched Satellite Wi-Fi powered by Starlink across the Malta ↔ Sicily crossing, added a Club Class subsection to Travel Info, and stood up a new Onboard Experience page in the brand hub. Stale 'Complimentary Wi-Fi onboard' USP bullet replaced with the accurate paid/Club-Class tiering.",
    capabilities: [
      "Internet & Streaming Package: €4.00 for 2 hours of full internet access including streaming services (video, music, apps)",
      "Club Class passengers receive a complimentary voucher for the 2-hour Internet & Streaming package — included in every Club Class ticket",
      "Wi-Fi is paid for standard tickets and complimentary for Club Class — never describe it as 'free Wi-Fi for everyone'",
      "Travel Info now has a dedicated Club Class section (premium saloon, lounge accessible by lift, Starlink voucher) — distinct from the existing accessibility note",
      "New Onboard Experience page (/onboard-experience) is the source of truth for connectivity, premium tiers, and onboard amenities; content auto-feeds into the agent's brand prompt",
    ],
  },
  {
    sortKey: "2026-04-25-a",
    date: "2026-04-25",
    category: "Current Offers",
    summary: "Added the Virtu Ferries commercial vehicles offer (round trip, up to 5.9m, driver included). Tiered by vehicle length with a flat ETS surcharge per tier. Sourced from virtuferries.com via the in-admin site scraper.",
    capabilities: [
      "Commercial round-trip rates (driver ticket included): up to 4.5m €413+€67.60 ETS · up to 5.0m €520+€74.60 ETS · up to 5.5m €581+€81.60 ETS · up to 5.9m €676+€88.60 ETS",
      "Second driver travels FREE — pays charges only",
      "Offer NOT applicable to refrigerated/fresh products, livestock, or live plants",
      "Treated as a current product alongside passenger offers; surfaces in the offers page, monthly planning snapshot, and the agent's auto-fed brand prompt",
    ],
  },
  {
    sortKey: "2026-04-23-a",
    date: "2026-04-23",
    category: "Travel Info / Operational Rules",
    summary: "Authoritative travel info absorbed from virtuferries.com/travel-info/5. Use these rules as ground truth when answering passenger-facing questions or writing service/info content.",
    capabilities: [
      "Booking: payment within 48h of advance reservation; bookings within 3 days of departure must be paid same day; online bookings paid immediately; unpaid reservations auto-cancelled without notice",
      "Booking info needed — passengers: full name, DOB, ID/passport number, nationality, mobile, email. Vehicles: make, model, registration",
      "Foot passenger check-in opens 2h before departure, closes 30 min before. Arrive 1h before scheduled departure",
      "Personal luggage: max 3 pieces per person, each up to 50×40×80cm (170 linear cm), stowed in baggage trolley/storage. Plus 1 hand luggage 37×45×25cm and ≤5kg carried to seat",
      "Cars: pack as much as you like (no luggage limit), incl. sports gear and family pets. No illegal/dangerous goods. Arrive 90 min before departure. Loading order is at Master/Duty Officer's discretion (safety/logistics, not first-come)",
      "Caravans charged at non-commercial light vehicle tariffs",
      "Pets — must be declared at booking, valid pet passport + vaccinations required, notify crew on boarding. Pets NOT allowed on coach transfers (except guide dogs). Recommend evening or early-morning sailings (cooler)",
      "Pet travel options (4): (1) Pet Cabin — A/C, insulated, cages provided by company, water/food by owner, charged, pre-book required, max 1 pet per cage. Cage 1: 60×80×60cm. Cages 2-4: 73×102×76.5cm. Cages 5-7: 105×115×90cm. (2) Pets in Vehicles — kept in car with windows open, first 3 pets free. (3) Pets on outside deck — cats/dogs only, leak-proof cage max 91×64×67.5cm, owner must accompany, leash + muzzle when transiting through passenger areas, charged. (4) Small pets in passenger areas — cats/dogs only in leak-proof carrier max 70×50×51.5cm, must stay inside carrier, on floor next to seat, never on tables/seats",
      "Service & Guide Dogs welcome on board. Must be certified by ADI or IGDF. Must wear identifying jacket and harness throughout voyage",
      "Pets are NOT allowed in passenger saloons/common areas (except small-pets-in-carrier rule and guide dogs). Master may permit owner to visit pet in garage/cabin during voyage with crew escort",
      "Malta pet authority: Veterinary Regulation Directorate +356 9917 0532, petstravel.mafa@gov.mt. Pozzallo: Ufficio Sanita Pubblica Veterinaria Ragusa +39 0932 234958/960/613, igiene.allevamenti@asp.rg.it",
      "Accessibility: vessel has ramps, lift, accessible toilet. Euro Class & Club Class lounges accessible by lift. Passengers with reduced mobility encouraged to notify at booking. Disability Card holders accommodated",
      "Commercial vehicles: dangerous-goods rules per IMDG Code (see Conditions of Carriage). Commercial drivers have a designated lounge",
      "Bicycles travel free, subject to space — must be declared at booking",
      "Travel info reference page: virtuferries.com/travel-info/5. Refund policy & conditions: Conditions of Carriage at virtuferries.com/terms_and_conditions/23",
    ],
  },
  {
    sortKey: "2026-04-16-k",
    date: "2026-04-16",
    category: "Current Offers",
    summary: "Saturday Night in Malta (SNF) offer extended indefinitely. Treat as a permanent weekend product, not a seasonal Jan–Apr promo.",
    capabilities: [
      "SNF offer no longer has an end date — running ongoing as of April 2026",
      "Position SNF as a year-round weekend product, not a limited-time promo (no urgency framing tied to expiry)",
      "Pricing and schedule unchanged: €57.00 per person return, 20:30 Sat departure from Pozzallo, 06:30 Sun return",
      "Hook remains 'Out Saturday night, home Sunday morning' — time arbitrage angle still leads",
    ],
  },
  {
    sortKey: "2026-04-16-j",
    date: "2026-04-16",
    category: "Posting Cadence",
    summary: "Cadence updated to 25 posts per month per platform. Instagram strategy clarified: reuse Facebook content where possible, create IG-native posts when it doesn't translate.",
    capabilities: [
      "English market: 25 Facebook posts per month",
      "Italian market: 25 Facebook posts + 25 Instagram posts per month",
      "Instagram default: cross-post from Facebook where content is image/video-led and needs no link",
      "Instagram exception: platform-specific IG post created when FB post is link-heavy, long-form, or FB-native",
      "Generate-plan now targets 25 posts per market with even daily distribution",
    ],
  },
  {
    sortKey: "2026-04-16-i",
    date: "2026-04-16",
    category: "Content Pillars",
    summary: "Content pillars updated and expanded from 4 to 5. Each pillar now has a defined goal and tone register to guide content generation.",
    capabilities: [
      "Pillar 1 — Why VF: reasons to choose Virtu Ferries; crossing as the obvious, easy choice",
      "Pillar 2 — Why Sicily: destination-led content; sells Sicily so VF is the natural next step",
      "Pillar 3 — VF Recommends: curated local travel intel; positions VF as trusted guide not ticket seller",
      "Pillar 4 — Virtu Ferries Experience: on-board, crew, UGC, social proof; real people, real crossings",
      "Pillar 5 — Sicily Experience: immersive sensory content, no hard sell; let the island do the talking",
    ],
  },
  {
    sortKey: "2026-04-16-h",
    date: "2026-04-16",
    category: "Current Offers",
    summary: "Live offer pricing loaded into the agent. The agent now knows the three active offers, their prices, schedules, and how to use them as content material.",
    capabilities: [
      "One Day Offer: adult return €63.60, child €44.60, light car €109.00, motorbike €69.00",
      "More Than One Day Offer: adult return €63.60, light car €109.00 — extended until May 30, 2026",
      "Saturday Night in Malta (SNF): €57.00 per person return, 20:30 Saturday departure from Sicily, 06:30 Sunday return — running January–April 2026",
      "Offer copywriting rules: lead with human benefit, not price; SNF hook is 'Out Saturday night, home Sunday morning'",
      "Always directs to virtuferries.com for booking — never implies guaranteed availability",
    ],
  },
  {
    sortKey: "2026-04-16-g",
    date: "2026-04-16",
    category: "Company History & Fleet",
    summary: "Company heritage, fleet specifications, and scale data loaded. The agent now knows the founding story, vessel names and dimensions, annual volumes, and how to use this history as a creative and credibility asset.",
    capabilities: [
      "Founded 1988 in Malta — 36+ years of continuous operation, one of Malta's longest-serving transport institutions",
      "Fleet: Saint John Paul II (flagship, 110m, 900 pax, Incat 089, in service March 2019) and Jean de La Valette (106.5m, 800 pax, since 2010)",
      "Scale: 250,000+ passengers and 25,000+ vehicles annually — mainstream route, not niche",
      "All vessels fly the Maltese flag — local pride asset for English market content",
      "Year-round operation flagged as a genuine differentiator vs seasonal competitors",
      "Venezia Lines subsidiary: Adriatic routes, founded 2001, seasonal April–October",
      "Heritage framing guidance: use as credibility signal, not a boast; mainstream and familiar, not discovered",
    ],
  },
  {
    sortKey: "2026-04-16-f",
    date: "2026-04-16",
    category: "Operational Knowledge",
    summary: "Full operational knowledge base loaded into the brand agent. The agent can now answer detailed passenger questions about tickets, boarding, luggage, pets, car hire, excursions, and more.",
    capabilities: [
      "Knows both ticket classes in detail: Euro Class (Upper Deck, free seating) and Club Class (Bridge Deck, priority boarding, newspaper, OJ)",
      "Full vessel layout: 5 Upper Deck lounges, Bridge Deck, Hybleum shop, bars, pet cabin, facilities for reduced mobility",
      "Travel Made Simple policy: full refund 24h before, no no-show penalty, no name change fees, no date change fees within same fare",
      "Luggage rules by passenger type: foot passengers (3 bags + 1 hand luggage), car passengers (no restrictions)",
      "Four pet travel options with size limits, booking requirements, and weather restrictions",
      "Check-in times, required documents, minor travel rules, and document validity (incl. Italian Paper ID invalid from Aug 2026)",
      "Car hire in Pozzallo: vehicle groups, pricing, CDW options, refund policy",
      "Excursions by season: Syracuse, Ragusa Ibla, Taormina, Mt. Etna, and Malta in One Day",
      "Seasonal content intelligence: demand peaks, audience travel patterns, and month-by-month content opportunities",
    ],
  },
  {
    sortKey: "2026-04-16-e",
    date: "2026-04-16",
    category: "Approval & Learning",
    summary: "Content approval queue, rejection flow, and learning loop built. Preference data now injected into agent context before every content generation call.",
    capabilities: [
      "Agent approves and rejects posts one at a time, storing decisions in PostgreSQL",
      "Aggregates approval and rejection patterns over time — pillar, tone register, format, and market",
      "Surfaces active constraints automatically when a rejection reason appears 3 or more times",
      "Injects learned preferences into every brand-guidelines and social-expert content generation call silently",
      "Monthly Learning Summary card shows approved/rejected patterns and active constraints at the top of the Social Expert page",
      "Close Month archives all pending posts and logs a changelog entry summarising the month",
    ],
  },
  {
    sortKey: "2026-04-16-d",
    date: "2026-04-16",
    category: "Trend Adaptation",
    summary: "Trend Adaptation feature added to Social Media Expert page.",
    capabilities: [
      "Receive a trend as text, link, image, or any combination — analyse the core mechanic that makes it work",
      "Assess brand fit honestly — if the trend doesn't translate to a travel/ferry brand without feeling forced, declines to produce output",
      "Return one adapted content idea per applicable market (English, Italian, or both) when fit is confirmed",
      "Each idea includes a 2–3 line concept, a one-line explanation of why it works for VF, the target market, and the specific platform",
    ],
  },
  {
    sortKey: "2026-04-16-c",
    date: "2026-04-16",
    category: "Social Media Expert",
    summary: "Social Media Expert page built. Copy review, image review, and chat interface wired to OpenAI.",
    capabilities: [
      "Review copy against brand guidelines and return a structured verdict: On Brand / Needs Work / Off Brand",
      "Provide a plain-language explanation, specific suggestions, a rewritten version, and tone notes for any copy submitted",
      "Review images for brand fit using GPT-4o vision — same structured verdict output",
      "Maintain full conversational context within a chat session — follow-up questions build on previous answers",
      "Render markdown responses cleanly: tables, bullet lists, bold text, and structured plans",
    ],
  },
  {
    sortKey: "2026-04-16-b",
    date: "2026-04-16",
    category: "Brand Foundation",
    summary: "Brand guidelines system prompt added. Brand Identity and Social Media sections populated with real content.",
    capabilities: [
      "Agent now knows the full market structure: English market (Facebook, Maltese audience) and Italian market (Facebook + Instagram, Sicilian audience)",
      "Knows all four content pillars: Why VF, Why Sicily / Why Malta, VF Recommends, VF Experience",
      "Applies the correct tone register per context: Offer, Destination Spotlight, Operational, Cultural/Seasonal, UGC",
      "Follows the monthly briefing protocol — never produces a content plan without running a structured brief first",
      "Enforces promotional lead time rules: 4–6 weeks ahead, flags missed windows before outputting any plan",
      "Adapts trends to the VF brand with honest fit assessment — never forces output",
      "Cross-posting logic for Italian market: flags Cross-post Y/N with reasoning on every content piece",
      "Applies copy rules: banned words, exclamation mark discipline, CTA only when earned, register tuned by market",
    ],
  },
  {
    sortKey: "2026-04-16-a",
    date: "2026-04-16",
    category: "Initial Setup",
    summary: "Brand hub scaffolded with OpenAI brand agent, full brand identity, tone of voice guidelines, social media strategy, and content pillars for Virtu Ferries.",
    capabilities: [
      "Answer questions about Virtu Ferries brand identity, colours, fonts, and visual language",
      "Apply and explain the brand tone of voice — travel-forward, editorially sharp, warm but not gushing",
      "Generate on-brand social media content for Instagram, Facebook, X, and LinkedIn",
      "Advise on what to say and what not to say based on established messaging guidelines",
      "Provide context on the Malta–Sicily route, crossing time, and key brand messages",
    ],
  },
];

// Gozo Highspeed (brand_id 2) — fresh slate; will fill in as we go.
export const gozoKnowledgeChangelog: ChangelogEntryStatic[] = [
  {
    sortKey: "2026-05-06-d",
    date: "2026-05-06",
    category: "Content Calendar",
    summary: "Removed the separate Edit-post step from the post detail modal — caption, time, links, pillar, format, assigned-to, visual direction, resources and notes are now editable inline straight from the detail view.",
    capabilities: [
      "Click any field in the post detail modal to edit it in place; saves automatically on blur or Enter with a tiny saving / saved indicator",
      "Pillar, Format and Assigned-to use dropdowns (Assigned-to pulls from the existing team-member list); Date and Time use native pickers; URLs (link, Drive folder, visual reference) get one-click open after save",
      "The 'Edit post' button is gone — same affordances as the legacy edit modal, no extra step",
    ],
  },
  {
    sortKey: "2026-05-06-c",
    date: "2026-05-06",
    category: "Media Library",
    summary: "Each media asset can now carry a source-file link (Canva, PSD, Figma, Drive, Dropbox, etc.) so the editable original is always one click away from the rendered visual.",
    capabilities: [
      "Add, edit or remove a source URL on any asset from the preview modal — auto-prefixes https:// and labels the link by source (Canva, Figma, Drive, …)",
      "Asset cards show a small link icon when a source file is attached, so the team can spot which visuals have an editable original",
    ],
  },
  {
    sortKey: "2026-05-06-b",
    date: "2026-05-06",
    category: "Media Library",
    summary: "Added folder organisation to the Media Library, including a built-in Evergreen folder, the ability to create custom folders on the fly, and per-asset folder reassignment from the preview modal.",
    capabilities: [
      "Group uploaded media into folders (Evergreen by default; custom folders can be created any time) and filter the grid by active folder",
      "Move any existing asset between folders from its preview modal — the change persists and the folder pill counts update live",
      "When a folder is selected, new uploads land into that folder automatically, with a clear 'Uploading into …' indicator next to the upload button",
    ],
  },
  {
    sortKey: "2026-04-25-a",
    date: "2026-04-25",
    category: "Initial Setup",
    summary: "Brand hub initialised for Gozo Highspeed. No legacy posts or knowledge yet — the agent will learn the brand voice from scratch as content is added.",
    capabilities: [
      "Recognise that Gozo Highspeed is a separate brand from Virtu Ferries",
      "Wait for brand identity, voice notes, pillars and past posts before generating opinionated content",
      "Default to neutral, factual tone until brand voice is defined",
    ],
  },
];

// Brand-id → static seed entries.
export const brandKnowledgeChangelog: Map<number, ChangelogEntryStatic[]> = new Map([
  [1, knowledgeChangelog],
  [2, gozoKnowledgeChangelog],
]);
