import { Router, type IRouter } from "express";
import authRouter from "./auth.js";
import healthRouter from "./health.js";
import brandsRouter from "./brands.js";
import chatRouter from "./chat.js";
import changelogRouter from "./changelog.js";
import contentIdeasRouter from "./contentIdeas.js";
import openaiRouter from "./openai.js";
import contentRouter from "./content.js";
import storageRouter from "./storage.js";
import eventsRouter from "./events.js";
import gozoEventsRouter from "./gozoEvents.js";
import sicilyEventsRouter from "./sicilyEvents.js";
import teamMembersRouter from "./teamMembers.js";
import savedItemsRouter from "./savedItems.js";
import mediaAssetsRouter from "./mediaAssets.js";
import scraperRouter from "./scraper.js";
import sharesRouter from "./shares.js";
import templatesRouter from "./templates.js";
import printsRouter from "./prints.js";
import nicoLinksRouter from "./nicoLinks.js";
import nicoRequestsRouter from "./nicoRequests.js";
import designBriefsRouter from "./designBriefs.js";
import repostsRouter from "./reposts.js";
import brandResourcesRouter from "./brandResources.js";
import performanceReportsRouter from "./performanceReports.js";
import adminRouter from "./admin.js";
import accessAdminRouter from "./accessAdmin.js";
import allowedEmailsRouter from "./allowedEmails.js";
import facebookRouter from "./facebook.js";
import marketingRequestsRouter from "./marketingRequests.js";

const router: IRouter = Router();

router.use(authRouter);
router.use(adminRouter);
router.use(accessAdminRouter);
router.use(allowedEmailsRouter);
router.use(healthRouter);
router.use(brandsRouter);
router.use(chatRouter);
router.use(changelogRouter);
router.use(contentIdeasRouter);
router.use(openaiRouter);
router.use(contentRouter);
router.use(storageRouter);
router.use(eventsRouter);
router.use(gozoEventsRouter);
router.use(sicilyEventsRouter);
router.use(teamMembersRouter);
router.use(savedItemsRouter);
router.use(mediaAssetsRouter);
router.use(scraperRouter);
router.use(sharesRouter);
router.use(templatesRouter);
router.use(printsRouter);
router.use(nicoLinksRouter);
router.use(nicoRequestsRouter);
router.use(designBriefsRouter);
router.use(repostsRouter);
router.use(brandResourcesRouter);
router.use(performanceReportsRouter);
router.use(facebookRouter);
router.use(marketingRequestsRouter);

export default router;
